feature/customer-reviews
YanaZavodovskaya/goit-project-01-demo pull request #5
Opened 2022-07-08 12:07 UTC by VitaliyDeveloper

Добавил первые элементы и css для контейнера

2022-07-08 13:18 UTC, YanaZavodovskaya requested changes

2022-07-09 03:00 UTC, VitaliyDeveloper commented on src/partials/customer-reviews.html
> +    <img class="customer-photo" src="" alt="customer photo" />
Исправлено

2022-07-09 07:17 UTC, YanaZavodovskaya requested changes
Исправить классы. Добавить два нижних подчеркивания там где это необходимо. Пример `customer-reviews__reviews`

2022-07-09 07:51 UTC, YanaZavodovskaya approved these changes
Принято

2022-07-09 07:51 UTC, merged