Готовый хэдер для всех устройств
YanaZavodovskaya/goit-project-01-demo pull request #9
Opened 2022-07-08 21:15 UTC by ViktoryAm

Сделала готовый хэдэр для всех устройств. Кнопку Buy now еще не реализовывала. Займусь ей в последнюю очередь, когда все будет готово.

2022-07-08 21:22 UTC, YanaZavodovskaya requested changes

2022-07-08 21:22 UTC, YanaZavodovskaya commented on src/sass/layout/_header.scss
> +    font-weight: 700;
Здесь нужно использовать миксин для фонтов

2022-07-09 13:19 UTC, ViktoryAm commented on src/sass/layout/_header.scss
> +    font-weight: 700;
Исправлено

2022-07-09 13:37 UTC, YanaZavodovskaya requested changes
Удалить дополнительный класс item

2022-07-09 13:39 UTC, YanaZavodovskaya requested changes
Удалить дополнительный класс item

2022-07-09 13:42 UTC, ViktoryAm commented
Исправила

2022-07-09 13:49 UTC, YanaZavodovskaya approved these changes

2022-07-09 13:49 UTC, merged